name: checkingtype
on:
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually 
  
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID: 
        required: true
jobs:

  snapshot:
    runs-on: ubuntu-latest
    steps:

      - name: Pipeline Trigger
        run: echo "first step"
