name: Swagger deploy
on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Pipeline Trigger
        run: echo "first step"
        
#       - uses: convictional/trigger-workflow-and-wait@v1.3.0
#         with:
#           owner: MODE-POC
#           repo: Code-security
#           github_token: ${{ secrets.ACCESS_TOKEN }}
