name: Stage
on:
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually,
  #schedule:
     #- cron: '0 16 21 8 *'
jobs:

 Run_qc_imaging_pipeline:
    uses: ./.github/workflows/checking.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DEVOPS_SSH_PRIVATE_KEY: ${{ secrets.DEVOPS_SSH_PRIVATE_KEY }}
      MS_DEVOPS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_DEVOPS_TEAMS_WEBHOOK_URI }}
      BASTION_KNOWN_HOSTS: ${{ secrets.BASTION_KNOWN_HOSTS }}

 schedule_validation:
    runs-on: ubuntu-latest
    steps:
      - name: cron
        run: sleep 30        

 Run_qc_tms_pipeline:
    needs: [schedule_validation, Run_qc_imaging_pipeline]
    if: always ()
    uses: ./.github/workflows/checking.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DEVOPS_SSH_PRIVATE_KEY: ${{ secrets.DEVOPS_SSH_PRIVATE_KEY }}
      MS_DEVOPS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_DEVOPS_TEAMS_WEBHOOK_URI }}
      BASTION_KNOWN_HOSTS: ${{ secrets.BASTION_KNOWN_HOSTS }}

 Run_staging_btms_pipeline:
    runs-on: ubuntu-latest
    needs: [Run_qc_imaging_pipeline, Run_qc_tms_pipeline]
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run QC TMS Pipeline
        uses: ./.github/workflows/checking.yml
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEVOPS_SSH_PRIVATE_KEY: ${{ secrets.DEVOPS_SSH_PRIVATE_KEY }}
          MS_DEVOPS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_DEVOPS_TEAMS_WEBHOOK_URI }}
          BASTION_KNOWN_HOSTS: ${{ secrets.BASTION_KNOWN_HOSTS }}

      - name: Delay for 10 minutes
        run: sleep 600

    # runs-on: ubuntu-latest
    # needs: [Run_qc_imaging_pipeline, Run_qc_tms_pipeline]
    # if: always()
    # steps:
    #   - name: Delay for 15 mins
    #     run: sleep 30
    #   - name: uses
    #     uses: ./.github/workflows/checking.yml
    #     with:
    #        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #        DEVOPS_SSH_PRIVATE_KEY: ${{ secrets.DEVOPS_SSH_PRIVATE_KEY }}
    #        MS_DEVOPS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_DEVOPS_TEAMS_WEBHOOK_URI }}
    #        BASTION_KNOWN_HOSTS: ${{ secrets.BASTION_KNOWN_HOSTS }}
