name: Stage
on:
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually,
  schedule:
     - cron: '0 5 23 8 *'
jobs:
 Run_qc_imaging_pipeline:
    uses: ./.github/workflows/checking.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DEVOPS_SSH_PRIVATE_KEY: ${{ secrets.DEVOPS_SSH_PRIVATE_KEY }}
      MS_DEVOPS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_DEVOPS_TEAMS_WEBHOOK_URI }}
      BASTION_KNOWN_HOSTS: ${{ secrets.BASTION_KNOWN_HOSTS }}      

 Run_qc_tms_pipeline:
    uses: ./.github/workflows/checking.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DEVOPS_SSH_PRIVATE_KEY: ${{ secrets.DEVOPS_SSH_PRIVATE_KEY }}
      MS_DEVOPS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_DEVOPS_TEAMS_WEBHOOK_URI }}
      BASTION_KNOWN_HOSTS: ${{ secrets.BASTION_KNOWN_HOSTS }}

 Sleep1:
    runs-on: ubuntu-latest
    needs: [Run_qc_imaging_pipeline, Run_qc_tms_pipeline]
    if: always ()
    steps:
      - name: cron
        run: sleep 15

 Run_staging_btms_pipeline:
    needs: [Sleep1,Run_qc_imaging_pipeline,Run_qc_tms_pipeline]
    if: always ()
    uses: ./.github/workflows/checking.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DEVOPS_SSH_PRIVATE_KEY: ${{ secrets.DEVOPS_SSH_PRIVATE_KEY }}
      MS_DEVOPS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_DEVOPS_TEAMS_WEBHOOK_URI }}
      BASTION_KNOWN_HOSTS: ${{ secrets.BASTION_KNOWN_HOSTS }}

 Run_staging_btms_history_pipeline:
    needs: [Sleep1, Run_qc_imaging_pipeline, Run_qc_tms_pipeline]
    if: always ()
    uses: ./.github/workflows/checking.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DEVOPS_SSH_PRIVATE_KEY: ${{ secrets.DEVOPS_SSH_PRIVATE_KEY }}
      MS_DEVOPS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_DEVOPS_TEAMS_WEBHOOK_URI }}
      BASTION_KNOWN_HOSTS: ${{ secrets.BASTION_KNOWN_HOSTS }}

 Sleep2:
   runs-on: ubuntu-latest
   needs: [ Run_staging_btms_pipeline,  Run_staging_btms_history_pipeline]
   if: always ()
   steps:
     - name: cron
       run: sleep 15
        
 Run_staging_imaging_pipeline:
    needs: [Sleep2,  Run_staging_btms_pipeline,  Run_staging_btms_history_pipeline]
    if: always ()
    uses: ./.github/workflows/checking.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DEVOPS_SSH_PRIVATE_KEY: ${{ secrets.DEVOPS_SSH_PRIVATE_KEY }}
      MS_DEVOPS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_DEVOPS_TEAMS_WEBHOOK_URI }}
      BASTION_KNOWN_HOSTS: ${{ secrets.BASTION_KNOWN_HOSTS }}

 Run_staging_tms_pipeline:
    needs: [Sleep2,  Run_staging_btms_pipeline,  Run_staging_btms_history_pipeline]
    if: always ()
    uses: ./.github/workflows/checking.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DEVOPS_SSH_PRIVATE_KEY: ${{ secrets.DEVOPS_SSH_PRIVATE_KEY }}
      MS_DEVOPS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_DEVOPS_TEAMS_WEBHOOK_URI }}
      BASTION_KNOWN_HOSTS: ${{ secrets.BASTION_KNOWN_HOSTS }}
