name: Database Sync - Tuesday

on:
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *'
     
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Job1 Testing
        run: echo "Job1 first"
        
  Job2:
    runs-on: ubuntu-latest
    steps:
      - name: Job2 Testing
        run: echo "Job2 Second"
        
  Job3:
    runs-on: ubuntu-latest
    needs: [Job1, Job2]
    steps:
      - name: Delay for 15 minutes
        run: sleep 30 # 900 seconds = 15 minutes
      - name: Job3 Testing
        run: echo "Job3 Third"
