name: Database Sync - Tuesday

on:
  workflow_dispatch:
  #schedule:
    #- cron: '*/2 * * * *'
     
jobs:
  dev-btms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Job1 Testing
        run: echo "Job1 first"
      #- name: Intentionally fail Job 1
        #run: exit 1    
        
  dev-btms-history:
    runs-on: ubuntu-latest
    steps:
      #- name: Job2 Testing
        #run: echo "Job2 Second"
      - name: Intentionally fail Job 2
        run: exit 1  
        
  dev-tms:
    runs-on: ubuntu-latest
    needs: [dev-btms, dev-btms-history]
    if: always() # always run even if a previous step fails
    steps:
      - name: Delay for 30 sec
        run: sleep 30 # 900 seconds = 15 minutes
      - name: Job3 Testing
        run: echo "Job3 Third"
      #- name: Intentionally fail Job 3
        #run: exit 1    
        
  dev-imaging:
    runs-on: ubuntu-latest
    needs: [dev-btms, dev-btms-history]
    if: always() # always run even if a previous step fails
    steps:
      - name: Delay for 30 sec
        run: sleep 30 # 900 seconds = 15 minutes
      - name: Job4 Testing
        run: echo "Job4 Third" 
      - name: Intentionally fail Job 4
        run: exit 1    
        
        
  qc-btms:
    runs-on: ubuntu-latest
    needs: [dev-tms, dev-imaging]
    if: always() # always run even if a previous step fails
    steps:
      - name: Delay for 30 sec
        run: sleep 30 # 900 seconds = 15 minutes
      - name: Job5 Testing
        run: echo "Job5 Third"
      - name: Intentionally fail Job 4
        run: exit 1  
        
        
  qb-btms-history:
    runs-on: ubuntu-latest
    needs: [dev-tms, dev-imaging]
    if: always() # always run even if a previous step fails
    steps:
      - name: Delay for 30 sec
        run: sleep 30 # 900 seconds = 15 minutes
      - name: Job6 Testing
        run: echo "Job6 Third"
      #- name: Intentionally fail Job 4
        #run: exit 1  
