name: Find Latest Build Number
on:
  workflow_run:
    workflows: ["Stage"]
    types:
      - completed

jobs:
  find-latest-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Latest Build Number
        id: latest_build
        run: |
          TOKEN=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
          BRANCH_NAME=develop
          WORKFLOW_NAME="Stage DB Refresh - POC"

          LATEST_BUILD=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/workflows/$WORKFLOW_NAME/runs?branch=$BRANCH_NAME" \
            | jq -r '.workflow_runs | first | .run_number')

          echo "Latest build number for branch $BRANCH_NAME: $LATEST_BUILD"
          echo "::set-output name=latest_build::$LATEST_BUILD"

      - name: Check Pipeline Status
        run: |
          LATEST_BUILD_STATUS=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$LATEST_BUILD" \
            | jq -r '.conclusion')
          if [ "$LATEST_BUILD_STATUS" = "success" ]; then
            echo "Latest build was successful."
            # Perform additional actions for a successful build.
          else
            echo "Latest build failed or had other status: $LATEST_BUILD_STATUS."
            # Perform additional actions for a failed build or other statuses.
          fi
      - name: Get Previous Workflow Status
        id: get_status
        env:
          GITHUB_TOKEN: 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
          REPO_OWNER: ulageswaris
          REPO_NAME: POC-Public
          WORKFLOW_NAME: Stage
        run: |
          PREVIOUS_RUN_STATUS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/actions/workflows/$WORKFLOW_NAME/runs?per_page=1" | \
            jq -r '.workflow_runs[0].conclusion')
          echo "Previous Workflow Status: $PREVIOUS_RUN_STATUS"
