name: Find Latest Build Number
on:
  workflow_run:
    workflows: ["Stage DB Refresh - POC"]
    types:
      - completed

jobs:
  find-latest-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

 

      - name: Get Latest Build Number
        id: latest_build
        run: |
          TOKEN=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
          BRANCH_NAME=develop
          WORKFLOW_NAME="Stage DB Refresh - POC"

 

          LATEST_BUILD=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/workflows/$WORKFLOW_NAME/runs?branch=$BRANCH_NAME" \
            | jq -r '.workflow_runs | first | .run_number')

 

          echo "Latest build number for branch $BRANCH_NAME: $LATEST_BUILD"
          echo "::set-output name=latest_build::$LATEST_BUILD"

      - name: Use Latest Build Number
        run: echo "Latest build number is ${{ steps.latest_build.outputs.latest_build }}"
